services:
  nginx:
    image: nginx:alpine
    container_name: whoami-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "8443:8443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - whoami-net
    depends_on:
      - rathole

  rathole:
    image: rapiz1/rathole:latest
    container_name: whoami-rathole
    user: root
    restart: unless-stopped
    command: ["--server", "/app/server.toml"]
    ports:
      - "443:2333" # Маскируем Rathole под обычный HTTPS трафик!
    volumes:
      - ./rathole/server.toml:/app/server.toml
    networks:
      - whoami-net

  push-gateway:
    build: ./push-gateway
    container_name: whoami-push
    restart: unless-stopped
    # Порты наружу не пробрасываем! Доступ только внутри сети Docker для Nginx / Rathole
    environment:
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
    env_file:
      - .env
    networks:
      - whoami-net

networks:
  whoami-net:
    name: whoami-net
