serverAddr = "149.33.42.8"
serverPort = 7443

[auth]
method = "token"
token = "{{ .Envs.FRP_TOKEN }}"

[log]
level = "trace"

[[proxies]]
name = "pocketbase_prod"
type = "tcp"
localIP = "whoami-pb"
localPort = 8090
remotePort = 8090

[[proxies]]
name = "pocketbase_dev"
type = "tcp"
localIP = "whoami-pb-dev"
localPort = 8090
remotePort = 9090
