services:
  web:
    build:
      context: ../../app
      dockerfile: Dockerfile
    container_name: whoami-web
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - default

networks:
  default:
    name: whoami-net
    external: true
