[server]
# Порт, который слушает Rathole на VPS для приема соединений от домашнего сервера
bind_addr = "0.0.0.0:2333"

[server.services.pocketbase]
# Секретный токен (нужно сгенерировать сложную строку и указать тут и у клиента)
token = "Kx9m2PqL8vY5wR4nJc7t"
bind_addr = "0.0.0.0:8090" # Внутренний порт для проксирования на PB Prod
nodelay = true

[server.services.pocketbase_dev]
token = "y2N4vB7mZ9rP1qL5cW8x"
bind_addr = "0.0.0.0:9090" # Внутренний порт для проксирования на PB Dev
nodelay = true
