server {
    listen 80;
    server_name whoami.ninja api.whoami.ninja dev-api.whoami.ninja;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name whoami.ninja;

    ssl_certificate /etc/letsencrypt/live/api.whoami.ninja/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.whoami.ninja/privkey.pem;

    location / {
        proxy_pass http://whoami-frps:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location /livekit/ {
        proxy_pass http://127.0.0.1:7880/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 86400;
    }
}

server {
    listen 443 ssl;
    server_name api.whoami.ninja;

    ssl_certificate /etc/letsencrypt/live/api.whoami.ninja/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.whoami.ninja/privkey.pem;

    location / {
        proxy_pass http://whoami-frps:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location /push/ {
        proxy_pass http://whoami-push:4000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /livekit/ {
        proxy_pass http://127.0.0.1:7880/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 86400;
    }
}

server {
    listen 443 ssl;
    server_name dev-api.whoami.ninja;

    ssl_certificate /etc/letsencrypt/live/api.whoami.ninja/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.whoami.ninja/privkey.pem;

    location / {
        proxy_pass http://whoami-frps:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}
