/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthPrivateRouteImport } from './routes/_auth/private'
import { Route as AuthFavoritesRouteImport } from './routes/_auth/favorites'
import { Route as AuthContactsRouteImport } from './routes/_auth/contacts'
import { Route as AuthChatRouteImport } from './routes/_auth/chat'
import { Route as AuthCallsRouteImport } from './routes/_auth/calls'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthPrivateIndexRouteImport } from './routes/_auth/private/index'
import { Route as AuthChatIndexRouteImport } from './routes/_auth/chat/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthSettingsSecurityRouteImport } from './routes/_auth/settings/security'
import { Route as AuthSettingsPrivacyRouteImport } from './routes/_auth/settings/privacy'
import { Route as AuthSettingsNotificationsRouteImport } from './routes/_auth/settings/notifications'
import { Route as AuthSettingsAppearanceRouteImport } from './routes/_auth/settings/appearance'
import { Route as AuthSettingsAccountRouteImport } from './routes/_auth/settings/account'
import { Route as AuthFavoritesRoomIdRouteImport } from './routes/_auth/favorites.$roomId'
import { Route as AuthDmUserIdRouteImport } from './routes/_auth/dm.$userId'
import { Route as AuthChatRoomIdRouteImport } from './routes/_auth/chat/$roomId'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPrivateRoute = AuthPrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFavoritesRoute = AuthFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsRoute = AuthContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatRoute = AuthChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallsRoute = AuthCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthPrivateIndexRoute = AuthPrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPrivateRoute,
} as any)
const AuthChatIndexRoute = AuthChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthChatRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthSettingsSecurityRoute = AuthSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsPrivacyRoute = AuthSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsNotificationsRoute =
  AuthSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsAppearanceRoute = AuthSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsAccountRoute = AuthSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthFavoritesRoomIdRoute = AuthFavoritesRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => AuthFavoritesRoute,
} as any)
const AuthDmUserIdRoute = AuthDmUserIdRouteImport.update({
  id: '/dm/$userId',
  path: '/dm/$userId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatRoomIdRoute = AuthChatRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => AuthChatRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/calls': typeof AuthCallsRoute
  '/chat': typeof AuthChatRouteWithChildren
  '/contacts': typeof AuthContactsRoute
  '/favorites': typeof AuthFavoritesRouteWithChildren
  '/private': typeof AuthPrivateRouteWithChildren
  '/profile': typeof AuthProfileRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/admin/users': typeof AuthAdminUsersRoute
  '/chat/$roomId': typeof AuthChatRoomIdRoute
  '/dm/$userId': typeof AuthDmUserIdRoute
  '/favorites/$roomId': typeof AuthFavoritesRoomIdRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/privacy': typeof AuthSettingsPrivacyRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/chat/': typeof AuthChatIndexRoute
  '/private/': typeof AuthPrivateIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calls': typeof AuthCallsRoute
  '/contacts': typeof AuthContactsRoute
  '/favorites': typeof AuthFavoritesRouteWithChildren
  '/profile': typeof AuthProfileRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/chat/$roomId': typeof AuthChatRoomIdRoute
  '/dm/$userId': typeof AuthDmUserIdRoute
  '/favorites/$roomId': typeof AuthFavoritesRoomIdRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/privacy': typeof AuthSettingsPrivacyRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/admin': typeof AuthAdminIndexRoute
  '/chat': typeof AuthChatIndexRoute
  '/private': typeof AuthPrivateIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/calls': typeof AuthCallsRoute
  '/_auth/chat': typeof AuthChatRouteWithChildren
  '/_auth/contacts': typeof AuthContactsRoute
  '/_auth/favorites': typeof AuthFavoritesRouteWithChildren
  '/_auth/private': typeof AuthPrivateRouteWithChildren
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/chat/$roomId': typeof AuthChatRoomIdRoute
  '/_auth/dm/$userId': typeof AuthDmUserIdRoute
  '/_auth/favorites/$roomId': typeof AuthFavoritesRoomIdRoute
  '/_auth/settings/account': typeof AuthSettingsAccountRoute
  '/_auth/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/_auth/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/_auth/settings/privacy': typeof AuthSettingsPrivacyRoute
  '/_auth/settings/security': typeof AuthSettingsSecurityRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/chat/': typeof AuthChatIndexRoute
  '/_auth/private/': typeof AuthPrivateIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/calls'
    | '/chat'
    | '/contacts'
    | '/favorites'
    | '/private'
    | '/profile'
    | '/settings'
    | '/admin/users'
    | '/chat/$roomId'
    | '/dm/$userId'
    | '/favorites/$roomId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/security'
    | '/admin/'
    | '/chat/'
    | '/private/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/calls'
    | '/contacts'
    | '/favorites'
    | '/profile'
    | '/admin/users'
    | '/chat/$roomId'
    | '/dm/$userId'
    | '/favorites/$roomId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/security'
    | '/admin'
    | '/chat'
    | '/private'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/admin'
    | '/_auth/calls'
    | '/_auth/chat'
    | '/_auth/contacts'
    | '/_auth/favorites'
    | '/_auth/private'
    | '/_auth/profile'
    | '/_auth/settings'
    | '/_auth/admin/users'
    | '/_auth/chat/$roomId'
    | '/_auth/dm/$userId'
    | '/_auth/favorites/$roomId'
    | '/_auth/settings/account'
    | '/_auth/settings/appearance'
    | '/_auth/settings/notifications'
    | '/_auth/settings/privacy'
    | '/_auth/settings/security'
    | '/_auth/admin/'
    | '/_auth/chat/'
    | '/_auth/private/'
    | '/_auth/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/private': {
      id: '/_auth/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof AuthPrivateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/favorites': {
      id: '/_auth/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthFavoritesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts': {
      id: '/_auth/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthContactsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat': {
      id: '/_auth/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthChatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calls': {
      id: '/_auth/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthCallsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/private/': {
      id: '/_auth/private/'
      path: '/'
      fullPath: '/private/'
      preLoaderRoute: typeof AuthPrivateIndexRouteImport
      parentRoute: typeof AuthPrivateRoute
    }
    '/_auth/chat/': {
      id: '/_auth/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthChatIndexRouteImport
      parentRoute: typeof AuthChatRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/settings/security': {
      id: '/_auth/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthSettingsSecurityRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/privacy': {
      id: '/_auth/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthSettingsPrivacyRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/notifications': {
      id: '/_auth/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthSettingsNotificationsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/appearance': {
      id: '/_auth/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthSettingsAppearanceRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/account': {
      id: '/_auth/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthSettingsAccountRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/favorites/$roomId': {
      id: '/_auth/favorites/$roomId'
      path: '/$roomId'
      fullPath: '/favorites/$roomId'
      preLoaderRoute: typeof AuthFavoritesRoomIdRouteImport
      parentRoute: typeof AuthFavoritesRoute
    }
    '/_auth/dm/$userId': {
      id: '/_auth/dm/$userId'
      path: '/dm/$userId'
      fullPath: '/dm/$userId'
      preLoaderRoute: typeof AuthDmUserIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat/$roomId': {
      id: '/_auth/chat/$roomId'
      path: '/$roomId'
      fullPath: '/chat/$roomId'
      preLoaderRoute: typeof AuthChatRoomIdRouteImport
      parentRoute: typeof AuthChatRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthAdminRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthChatRouteChildren {
  AuthChatRoomIdRoute: typeof AuthChatRoomIdRoute
  AuthChatIndexRoute: typeof AuthChatIndexRoute
}

const AuthChatRouteChildren: AuthChatRouteChildren = {
  AuthChatRoomIdRoute: AuthChatRoomIdRoute,
  AuthChatIndexRoute: AuthChatIndexRoute,
}

const AuthChatRouteWithChildren = AuthChatRoute._addFileChildren(
  AuthChatRouteChildren,
)

interface AuthFavoritesRouteChildren {
  AuthFavoritesRoomIdRoute: typeof AuthFavoritesRoomIdRoute
}

const AuthFavoritesRouteChildren: AuthFavoritesRouteChildren = {
  AuthFavoritesRoomIdRoute: AuthFavoritesRoomIdRoute,
}

const AuthFavoritesRouteWithChildren = AuthFavoritesRoute._addFileChildren(
  AuthFavoritesRouteChildren,
)

interface AuthPrivateRouteChildren {
  AuthPrivateIndexRoute: typeof AuthPrivateIndexRoute
}

const AuthPrivateRouteChildren: AuthPrivateRouteChildren = {
  AuthPrivateIndexRoute: AuthPrivateIndexRoute,
}

const AuthPrivateRouteWithChildren = AuthPrivateRoute._addFileChildren(
  AuthPrivateRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsAccountRoute: typeof AuthSettingsAccountRoute
  AuthSettingsAppearanceRoute: typeof AuthSettingsAppearanceRoute
  AuthSettingsNotificationsRoute: typeof AuthSettingsNotificationsRoute
  AuthSettingsPrivacyRoute: typeof AuthSettingsPrivacyRoute
  AuthSettingsSecurityRoute: typeof AuthSettingsSecurityRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsAccountRoute: AuthSettingsAccountRoute,
  AuthSettingsAppearanceRoute: AuthSettingsAppearanceRoute,
  AuthSettingsNotificationsRoute: AuthSettingsNotificationsRoute,
  AuthSettingsPrivacyRoute: AuthSettingsPrivacyRoute,
  AuthSettingsSecurityRoute: AuthSettingsSecurityRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthCallsRoute: typeof AuthCallsRoute
  AuthChatRoute: typeof AuthChatRouteWithChildren
  AuthContactsRoute: typeof AuthContactsRoute
  AuthFavoritesRoute: typeof AuthFavoritesRouteWithChildren
  AuthPrivateRoute: typeof AuthPrivateRouteWithChildren
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthDmUserIdRoute: typeof AuthDmUserIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthCallsRoute: AuthCallsRoute,
  AuthChatRoute: AuthChatRouteWithChildren,
  AuthContactsRoute: AuthContactsRoute,
  AuthFavoritesRoute: AuthFavoritesRouteWithChildren,
  AuthPrivateRoute: AuthPrivateRouteWithChildren,
  AuthProfileRoute: AuthProfileRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthDmUserIdRoute: AuthDmUserIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
