#!/bin/sh
# Husky pre-commit hook

# Если мы уже в папке app (проверяем по наличию package.json), просто запускаем lint-staged
if [ -f "package.json" ]; then
    npx lint-staged
else
    # Иначе пробуем зайти в app
    cd app && npx lint-staged
fi
