services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    pull_policy: if_not_present
    container_name: whoami-pb-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8090 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: 
      - serve 
      - --http=0.0.0.0:8090 
      - --dir=/pb/pb_data 
      - --hooksDir=/pb/pb_hooks
    ports:
      - "9090:8090" # Порт 9090 для DEV во внешний мир
    volumes:
      - /home/alex/whoami-bd-dev/pb_data:/pb/pb_data
      - ../home/pb_hooks:/pb/pb_hooks
      - ../home/pb_schema.json:/pb/pb_schema.json
    env_file:
      - ../../app/.env
    environment:
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY:-}
      - PB_PUSH_GATEWAY_URL=http://whoami-push:4000
      - PB_SMTP_HOST=mailpit
      - PB_SMTP_PORT=1025
      - PB_SMTP_TLS=false
    networks:
      - default

networks:
  default:
    name: whoami-net
    external: true
