services:
  frpc:
    image: fatedier/frpc:v0.58.1
    container_name: whoami-frpc
    restart: always
    command: ["-c", "/etc/frp/frpc.toml"]
    env_file:
      - ../../app/.env
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml
    network_mode: host
